### PR TITLE
Added Chessboard Art [Issue #1]

### PR DESCRIPTION
**Pull request by Pranav-JJ**
It includes a script that prints a chessboard with the chess pieces. [Part of fancy folder]
[To execute it, I have used: `bash chess_board.sh`, since I work on WSL]

### CODE REVIEW

**Comment by Animeshz** [comment]
Also, executable bit seems to be missing, can you do a `chmod +x fancy/*`?

**Comment by Pranav-JJ** [comment]
Apologies, I followed your way and performed `chmod +x fancy/*`, however while adding files it only adds the rest of the files and not my own. Am I doing something wrong?
image
image

**Comment by Animeshz** [comment]
Nevermind, I'll just apply the quickfix myself.

LGTM :tada:, Thanks for the contribution.

**Comment by Pranav-JJ** [comment]
Thank you @Animeshz. If possible do lmk what I did wrong for the same, so I can keep it in mind for future contributions. Apologies for the confusion caused.

**Comment by Animeshz** [comment]
I don't know its probably vscode converting LF with CRLF character or adds a newline automatically which made the files changed and thus when adding it to git, it becomes modified. Its always a hassle to work on windows actually.

**Comment by Pranav-JJ** [comment]
I see, guess I'll look into alternatives for it then.

**Pull request merged**
