### PR TITLE
Added New Script to #1

### PR DESCRIPTION
**Pull request by rishirajm007**
I have added a new script to the fancy folder. It is an animation of a progress bar.
Please review it.😀

### CODE REVIEW

**Comment by Animeshz** [comment]
Screen seems to be flickering with the two animations running in parallel on the stdout, is there something I'm missing?

**Comment by rishirajm007** [comment]
I believe this phenomenon is occurring due to the alterations in the words preceding the commencement of the progress bar animation.

**Comment by Animeshz** [comment]
Nope, its clearly two outputs being written simultaneously because of a job spawned in parallel with `&`. Check if its really the intended behavior.

**Comment by rishirajm007** [comment]
I have implemented the recommended modification, and I hope that it now functions correctly. I kindly request your review and feedback on the changes. Thank you for your assistance.
@Animeshz

**Comment by Animeshz** [comment]
Almost done, just the width is 2x of what 100% should be.
23-10-24-18h18m21s

**Comment by rishirajm007** [comment]
@Animeshz 
I have rectified the width issue. Kindly request your formal review of the changes at your earliest convenience. Thank you for your time and consideration. :)

**Pull request merged**
